export const Actions = {
  APP_LOADING: 'APP_LOADING',
  APP_ERROR: 'APP_ERROR',
  APP_RESET: 'APP_RESET',
  USER_SET: 'USER_SET',
  USER_SET_PENDING_PURCHASES: 'USER_SET_PENDING_PURCHASES',
  PURCHASE_CONTRACT_SET: 'PURCHASE_CONTRACT_SET',
};

export const Routes = {
  CREATE_ACCOUNT: '/account/create',
  UNLOCK_ACCOUNT: '/account/unlock',
};
